### PR TITLE
Terratest

### PR DESCRIPTION
**Pull request by michaelamattes**
add new test structure  abd first terratest workflow

### CODE REVIEW

**Comment by michaelamattes** [comment]
@schurzi @rndmh3ro Is this the right place for test definitions or should we create a seperate repo for our tests, what did you mean ?

**Comment by schurzi** [comment]
I am not in favor of having go code in this repository. I am fine with adding the github workflow here, since it is the right place for that. The go code should be in a separate place. I currently lack understanding to decide the actual place for this code.  
From my understanding it may be best to use a pre-existing terratest action and then include the test code in the respective repositories for each terraform module separately.

**Comment by michaelamattes** [comment]
I've created a testrepo and an own github action for the go tests. The new behaviour could be look so.

* we Create an own Repo which includes go code and action definition e.g. https://github.com/michaelamattes/test-action
* in this repo we would only include the workflow which could be look so 
```
---
name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - name: Prepare Test Setup
        run: cat examples/min_main.tf | sed 's/\<source\>.*/source = "..\/"/g' > tests/main.tf
        working-directory: .

      - name: Checkout Github Action
        uses: actions/checkout@v3
        with:
          repository: michaelamattes/test-action
          ref: main
          path: ./testaction
          token: 'xxxx'

      - name: Run Test
        uses: ./testaction
        with:
          tool: terratest
          test: azure
          debug: true
```

What would you think @schurzi @rndmh3ro ?

**Comment by schurzi** [comment]
I think the step `Checkout Github Action` should not be needed, instead the Action should be included like all the other Actions via `uses:`. But the general approach seems ok. I'm also ok with us experimenting a bit to find a good solution. :)

**Comment by michaelamattes** [comment]
Update to new terratest-action repo - actually I need the checkout of the action so that the go code is located within the repository where it should run. Maybe i found a better solution after the first full setup tests.

**Review by rndmh3ro — APPROVED** [review]
as discussed: please open a follow-up issue to check if we can use the action as it is supposed to be.

**Pull request merged**
